import data from "./recommended.json";
import type { BaekjoonProblem } from "./tier";

/**
 * Curated Baekjoon problems, grouped by the week whose topic they practise.
 * Generated by `npm run baekjoon`; see `scripts/fetch-baekjoon.mts` for where
 * the list comes from and why only the index is copied.
 *
 * Server-only in practice — importing this pulls in the whole list. Client
 * components take `./tier` instead.
 *
 * Built once as a Map rather than filtered per call: every week page asks for
 * its own slice during the static build.
 */
const byWeek = new Map<number, BaekjoonProblem[]>();
for (const problem of data.problems as BaekjoonProblem[]) {
  const list = byWeek.get(problem.week);
  if (list) list.push(problem);
  else byWeek.set(problem.week, [problem]);
}

const NONE: BaekjoonProblem[] = [];

export function recommendedForWeek(week: number): BaekjoonProblem[] {
  return byWeek.get(week) ?? NONE;
}

export const BAEKJOON_SOURCE = data.source;
export const TOTAL_RECOMMENDED = (data.problems as BaekjoonProblem[]).length;

export type { BaekjoonProblem } from "./tier";
