/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/codeDrill.ts
 * Command: astryx theme build src/theme/codeDrill.ts
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/// <reference path="./code-drill.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const codeDrillTheme: DefinedTheme;
